#!/usr/bin/env python3
"""Replace English menu group names with Chinese."""
import os

html_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'index.html')
with open(html_path, 'r', encoding='utf-8') as f:
    content = f.read()

# English -> Chinese mapping for group names
REPLACEMENTS = {
    # Public
    "name:'auth'": "name:'认证'",
    "name:'captcha'": "name:'验证码'",
    "name:'geetest'": "name:'极验验证'",
    "name:'products'": "name:'产品'",
    "name:'users'": "name:'用户'",
    "name:'payment-methods'": "name:'支付方式'",
    "name:'nav'": "name:'导航'",
    "name:'homepage'": "name:'首页'",
    "name:'downloads'": "name:'下载中心'",
    "name:'announcements'": "name:'公告'",
    "name:'news'": "name:'新闻中心'",
    "name:'help'": "name:'帮助中心'",
    "name:'knowledge'": "name:'知识库'",
    "name:'languages'": "name:'语言'",
    "name:'oauth'": "name:'OAuth登录'",
    "name:'banners'": "name:'轮播图'",
    "name:'marketplace'": "name:'交易市场'",
    "name:'solutions'": "name:'解决方案'",
    "name:'colocation'": "name:'托管服务'",
    "name:'password'": "name:'密码'",
    "name:'system'": "name:'系统'",
    "name:'settings'": "name:'设置'",
    "name:'promo-codes'": "name:'优惠码'",
    "name:'product-groups'": "name:'产品分组'",
    "name:'maintenance'": "name:'维护通知'",
    "name:'domain'": "name:'域名'",
    "name:'contact'": "name:'联系表单'",
    
    # User
    "name:'user'": "name:'个人资料'",
    "name:'login-logs'": "name:'登录日志'",
    "name:'hosts'": "name:'产品/主机'",
    "name:'cart'": "name:'购物车'",
    "name:'orders'": "name:'订单'",
    "name:'invoices'": "name:'账单'",
    "name:'tickets'": "name:'工单'",
    "name:'balance'": "name:'余额'",
    "name:'credit'": "name:'信用额度'",
    "name:'contacts'": "name:'联系人'",
    "name:'payment-gateways'": "name:'支付网关'",
    "name:'messages'": "name:'消息中心'",
    "name:'certification'": "name:'实名认证'",
    "name:'upgrades'": "name:'升降级'",
    "name:'contracts'": "name:'合同'",
    "name:'affiliate'": "name:'推介计划'",
    "name:'vouchers'": "name:'发票'",
    "name:'voucher-types'": "name:'发票抬头'",
    "name:'voucher-posts'": "name:'发票收件地址'",
    "name:'multi-renew'": "name:'批量续费'",
    "name:'api-logs'": "name:'API日志'",
    "name:'product-diverts'": "name:'产品转移'",
    "name:'system-logs'": "name:'系统日志'",
    "name:'sms'": "name:'短信'",
    "name:'email'": "name:'邮件'",
    "name:'ssl'": "name:'SSL证书'",
    "name:'ai-shopping'": "name:'AI购物助手'",
    "name:'v10cloud'": "name:'V10云'",
    
    # Admin
    "name:'login'": "name:'管理员认证'",
    "name:'dashboard'": "name:'仪表盘'",
    "name:'product-first-groups'": "name:'一级产品分组'",
    "name:'product-downloads'": "name:'产品下载'",
    "name:'product-custom-fields'": "name:'产品自定义字段'",
    "name:'orders-enhanced'": "name:'增强版订单'",
    "name:'invoices-enhanced'": "name:'增强版账单'",
    "name:'tickets-enhanced'": "name:'增强版工单'",
    "name:'friendly-links'": "name:'友情链接'",
    "name:'logs'": "name:'日志'",
    "name:'admins'": "name:'管理员'",
    "name:'oauth-providers'": "name:'OAuth提供商'",
    "name:'cron-tasks'": "name:'定时任务'",
    "name:'dcim'": "name:'DCIM管理'",
    "name:'plugins'": "name:'插件管理'",
    "name:'server-modules'": "name:'服务器模块'",
    "name:'server-groups'": "name:'服务器分组'",
    "name:'provisions'": "name:'自动开通'",
    "name:'provision'": "name:'开通配置'",
    "name:'provision-modules'": "name:'开通模块'",
    "name:'client-groups'": "name:'客户分组'",
    "name:'client-services'": "name:'客户服务'",
    "name:'user-manage'": "name:'用户管理'",
    "name:'user-remarks'": "name:'用户备注'",
    "name:'email-templates'": "name:'邮件模板'",
    "name:'menus'": "name:'菜单管理'",
    "name:'lang-keys'": "name:'语言键'",
    "name:'nav-groups'": "name:'导航分组'",
    "name:'log-records'": "name:'操作日志'",
    "name:'rules'": "name:'规则管理'",
    "name:'sales'": "name:'销售管理'",
    "name:'sale'": "name:'销售'",
    "name:'ticket-depts'": "name:'工单部门'",
    "name:'config'": "name:'系统配置'",
    "name:'product-config-groups'": "name:'产品配置组'",
    "name:'config-options'": "name:'配置选项'",
    "name:'config-servers'": "name:'配置服务器'",
    "name:'advanced-options'": "name:'高级选项'",
    "name:'batch-sync'": "name:'批量同步'",
    "name:'community'": "name:'社区管理'",
    "name:'cron-url'": "name:'URL定时任务'",
    "name:'dcim-cloud'": "name:'DCIM云管理'",
    "name:'link-causes'": "name:'关联原因'",
    "name:'link-knowledge'": "name:'关联知识库'",
    "name:'accounts'": "name:'账号管理'",
    "name:'public'": "name:'公开设置'",
    "name:'backup'": "name:'备份管理'",
    "name:'rbac-pages'": "name:'RBAC页面'",
    "name:'rule-middle'": "name:'规则中间件'",
    "name:'rule-manage'": "name:'规则管理'",
    "name:'setting'": "name:'站点设置'",
    "name:'captcha-config'": "name:'验证码配置'",
    "name:'ticket-deliver'": "name:'工单透传'",
    "name:'ticket-prereply'": "name:'工单预回复'",
    "name:'ticket-statuses'": "name:'工单状态'",
    "name:'user-tastes'": "name:'用户偏好'",
    "name:'log-record'": "name:'操作日志'",
    "name:'log-cleaner'": "name:'日志清理'",
    "name:'notifications'": "name:'通知管理'",
    "name:'email-suffixes'": "name:'邮箱后缀'",
    "name:'api-keys'": "name:'API密钥'",
    "name:'custom-fields'": "name:'自定义字段'",
    "name:'custom-field-values'": "name:'自定义字段值'",
    "name:'custom-field-groups'": "name:'自定义字段组'",
    "name:'binds'": "name:'绑定管理'",
    "name:'service-details'": "name:'服务详情'",
    "name:'agents'": "name:'代理商'",
    "name:'agent'": "name:'代理商'",
    "name:'developers'": "name:'开发者'",
    "name:'balances'": "name:'余额管理'",
    "name:'certifications'": "name:'认证管理'",
    "name:'client-care'": "name:'客户关怀'",
    "name:'client-contacts'": "name:'客户联系方式'",
    "name:'currencies'": "name:'货币管理'",
    "name:'get-user'": "name:'获取用户'",
    "name:'get-users'": "name:'获取用户列表'",
    "name:'interflows'": "name:'互通管理'",
    "name:'invoice-items'": "name:'账单条目'",
    "name:'menu-groups'": "name:'菜单分组'",
    "name:'clients'": "name:'客户列表'",
    "name:'aggregate-login'": "name:'聚合登录'",
    "name:'oauth-bind'": "name:'OAuth绑定'",
    "name:'payment'": "name:'支付管理'",
    "name:'product-transfer'": "name:'产品转移'",
    "name:'product-transfers'": "name:'产品转移记录'",
    "name:'rbac'": "name:'权限管理'",
    "name:'reports'": "name:'报表统计'",
    "name:'blacklist'": "name:'黑名单'",
    "name:'run-map'": "name:'运行地图'",
    "name:'site-settings'": "name:'站点设置'",
    "name:'system-messages'": "name:'系统消息'",
    "name:'upload'": "name:'文件上传'",
    "name:'upstream'": "name:'上游管理'",
    "name:'user-levels'": "name:'用户等级'",
    "name:'v10'": "name:'V10对接'",
    "name:'voucher-rate'": "name:'发票税率'",
    "name:'voucher-list'": "name:'发票列表'",
    "name:'voucher-detail'": "name:'发票详情'",
    "name:'voucher-status'": "name:'发票状态'",
    "name:'wechat'": "name:'微信管理'",
    "name:'zjmf-api'": "name:'魔方API对接'",
    "name:'ssl-certificates'": "name:'SSL证书'",
    "name:'email-logs'": "name:'邮件日志'",
    "name:'email-stats'": "name:'邮件统计'",
    "name:'email-support'": "name:'邮件支持'",
    "name:'upgrade-config'": "name:'升级配置'",
    "name:'upgrade'": "name:'升级'",
    "name:'renewal'": "name:'续费'",
    "name:'web-navs'": "name:'网站导航'",
    "name:'custom-pages'": "name:'自定义页面'",
    "name:'product-pages'": "name:'产品页面'",
    "name:'system-nav'": "name:'系统导航'",
    "name:'product-menus'": "name:'产品菜单'",
    "name:'web-pages'": "name:'网站页面'",
    "name:'menu-types'": "name:'菜单类型'",
    "name:'other-menus'": "name:'其他菜单'",
    "name:'two-menus'": "name:'二级菜单'",
    "name:'all-menus'": "name:'全部菜单'",
    "name:'menu-active'": "name:'菜单激活'",
    "name:'nav-types'": "name:'导航类型'",
    "name:'create-web-data'": "name:'创建网站数据'",
    "name:'direct'": "name:'直接管理'",
    "name:'hook-menus'": "name:'Hook菜单'",
    "name:'nav-links'": "name:'导航链接'",
    "name:'client-tracks'": "name:'客户跟踪'",
    "name:'expresses'": "name:'快递管理'",
    "name:'cancel-reasons'": "name:'注销原因'",
    "name:'base-infos'": "name:'基础信息'",
    "name:'user-downloads'": "name:'用户下载'",
    "name:'audit-logs'": "name:'审计日志'",
    "name:'backups'": "name:'备份管理'",
    "name:'cs'": "name:'客服管理'",
    "name:'ai-ticket'": "name:'AI工单'",
    "name:'acfp'": "name:'ACFP模块'",
    "name:'common'": "name:'公共接口'",
    "name:'info-notice'": "name:'信息公告'",
    "name:'gateways'": "name:'支付网关'",
    "name:'sms-countries'": "name:'短信国家'",
    "name:'system-info'": "name:'系统信息'",
    "name:'configs'": "name:'配置管理'",
    "name:'kb'": "name:'知识库'",
}

count = 0
for eng, chn in REPLACEMENTS.items():
    if eng in content:
        content = content.replace(eng, chn)
        count += 1

with open(html_path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Replaced {count} menu names")
